require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - vendor/**/*

Layout/LineLength:
  Exclude:
    - spec/**/*
    - jekyll-gensocial.gemspec

Metrics/BlockLength:
  Exclude:
    - spec/**/* 
